<?php
/* @var $this Vista */
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Pagina principal</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="error_titulo">
            <img src="<?php echo Config::$url ?>publico/core/img/alerta.png" alt="alerta de kintucms">
            ¡Oops ha ocurrido un error!
        </div>
        <?php if (!Config::$produccion) : ?>
            <div class="error_cuerpo">
                <fieldset>
                    <legend>Resumen</legend>
                    <p><?php echo $mensaje ?></p>
                </fieldset>
                <fieldset>
                    <legend>Detalle de error</legend>
                    <table border="1">
                        <tr>
                            <td><span>Url solicitada</span></td>
                            <td><?php echo Config::$url . Cnt::$sufijo_url . htmlspecialchars(Ruteo::$url) ?></td>
                        </tr>
                        <tr>
                            <td><span>Información</span></td>
                            <td><?php echo $detalle ?></td>
                        </tr>
                    </table>
                </fieldset>
            </div>
        <?php else: ?>
            <div class="error_cuerpo">
                <p><?php echo $this->config->error ?></p>
            </div>
        <?php endif; ?>
    </body>
</html>
