<?php
/* @var $this Vista */
?>
<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->titulo ?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div>
            <?php echo $region['reg_cabeza'] ?>
        </div>
        <div>
            <?php echo $region['reg_menu'] ?>
        </div>
        <div>
            <?php echo $region['reg_cuerpo'] ?>
        </div>
        <div>
            <?php echo $region['reg_pie'] ?>
        </div>
    </body>
</html>